# Generated by Django 4.0.3 on 2022-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255)),
                ("word", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[("en", "en"), ("en-us", "en-us")],
                        default="en-us",
                        max_length=50,
                    ),
                ),
                ("is_headword", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
